### ISSUE TITLE
[BUG] links to reference do not work unless the dropdown of the references is opened

### ISSUE THREAD

**Issue by Remi-Gau** [agahkarakuzu/oreoni#4]

**Comment by agahkarakuzu** [comment]
Was this the case on a certain page? When I click any of the references, the dropdown expands and the cited source is highlighted.

**Comment by Remi-Gau** [comment]
Check on the live version:

For example 

https://remi-gau.github.io/oreoni/01/introduction.html#id21

**Comment by agahkarakuzu** [comment]
![refissue](https://user-images.githubusercontent.com/9632322/182126361-18ab865a-ff34-4732-be48-2a3f2b9fd907.gif)

Interesting, this is from the link you provided. Which browser are you using? This is the behaviour both on Chrome and Brave.

**Comment by Remi-Gau** [comment]
Good catch.

Confirmed that it does work in Chrome but not Firefox 103.0 (64-bit)

Should we report to the jupyter book repo?

> The WebDev equivalent of "it works on my machine" is "it works on my browser"

**Comment by agahkarakuzu** [comment]
Interesting, I saw a lot of issues/tickets opened around similar problems in Mozilla devs. 

I think we could report this to the JB repo, so they can add in the documentation that [dropdowns](https://jupyterbook.org/en/stable/content/components.html#dropdowns) will not expand when links resolve into their content. If they offer a solution, we implement. If not, we can also add a tiny note for Mozilla users.

**Comment by Remi-Gau** [comment]
Issue opened.

**Comment by agahkarakuzu** [comment]
Thanks!
