### ISSUE TITLE
Re GitHub Actions

### ISSUE THREAD

**Issue by agahkarakuzu** [agahkarakuzu/oreoni#6]
@Remi-Gau I have updated the book to use the latest jupyter book release (v0.113), which was not on pip. 

So I created a new actions file: https://github.com/agahkarakuzu/oreoni/blob/main/.github/workflows/jbuild.yml 

Feel free to adapt this to your `Makefile` approach, as that script has a few more steps to it. 

The page is live https://agahkarakuzu.github.io/oreoni

There are some wrinkles to iron out, but mostly done :)

**Comment by Remi-Gau** [comment]
Is it not possible to pip install directly from the jupyter book repo instead of downloading it first?

**Comment by agahkarakuzu** [comment]
I think v0.13 is not on pypi. Or my local was out of date.

**Comment by agahkarakuzu** [comment]
BTW I disabled other two actions by switching trigger to a no existent branch.

**Comment by agahkarakuzu** [comment]
#7
